config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :companies do
    resources :jobs
  end
  
  match '/company', to: 'companies#index', via: 'get'
  get 'users/new'

  root 'home_pages#home'
  match '/signup1', to: 'users#new', via: 'get'

end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :jobs
	validates :title, presence: true, length: { minimum: 1 }
	
	def self.search(search)
		where("title LIKE ?", "%#{search}")
	end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :company

  def self.search(search)
  	where("profession LIKE ?", "%#{search}")
  	where("country LIKE ?", "%#{search}")
  	where("city LIKE ?", "%#{search}")

	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
  	@company = Company.paginate(page: params[:page], per_page: 5) 
   

    if params[:search]
      @companies = Company.search(params[:search]).order("created_at DESC")
    
          
      @jobs = Job.search(params[:search]).order("created_at DESC")

    else
      @companies = Company.all.order('created_at DESC')
      @jobs = Job.all.order('created_at DESC')
    
    end
  end

  def show
  	@company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
   
  end

  def create
  	@company = Company.new(company_params)

  	if @company.save
  	  redirect_to @company
    else
      render 'new'
    end
  end

  def update
    @company = Company.find(params[:id])

    if @company.update(company_params)
      redirect_to @company
    else
      render 'edit'
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy

    redirect_to companies_path
  end
  

  private
  	def company_params
  	  params.require(:company).permit(:title)
  	end
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  def home
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	def index
		@company = Company.find(params[:company_id])
		@job = @company.jobs.all
	end

	def show
		
		@company = Company.find(params[:company_id])
	    @job = @company.jobs.find(job_params)
	end

	def new
	end

	def create
	  @company = Company.find(params[:company_id])
	  @job = @company.jobs.create(job_params)

	  
	  redirect_to company_path(@company)
	end

	private
		def job_params
			params.require(:job).permit(:profession, :country, :city)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/companies/_company.html.erb
<ul>
<% @companies.each do |company| %>
  <li>
    <p><%= company.title %>
       | <%= link_to 'Show vacancies', company_path(company) %>
    </p>
  </li>
<% end %>
</ul>

app/views/companies/edit.html.erb
<h1>Редактирование компании</h1>

<%= form_for :company, url: company_path(@company), method: :patch do |f| %>
	<% if @company.errors.any? %>
		<div id="error">
			<h2>
				 <%= pluralize(@company.errors.count, "error") %> Название не сохранено
			</h2>
			<ul>
				<% @company.errors.full_message.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
		<% end %>
		<p>
	      <%= f.label :title %><br>
	      <%= f.text_field :title %>
	    </p>
	    <p>
	      <%= f.submit %>
	    </p>
<% end %>

app/views/companies/index.html.erb
<h1>All companies</h1>

<%= form_tag(companies_path, :method => 'get', id: 'search-form') do %>
  <p>
  	<%= text_field_tag :search, params[:search] %>
  	<%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<% if @companies.present?  %>
	<p>Есть
	<%= render @companies %>
	</p>
<% elsif @jobs.present? %>
  <%= render @jobs %>
<% else %>
 	<p>Нет совпадений <%= params[:search] %></p> 

<% end %>

<%= will_paginate @company %>

<ul>
<% @company.each do |company| %>
  <li>
    <p><%= company.title %>
       | <%= link_to 'Show vacancies', company_path(company) %>
    </p>
  </li>
<% end %>
</ul>

<%= will_paginate @company %>

app/views/companies/new.html.erb
<h1>New Company</h1>
<%= form_for :company, url: companies_path do |f| %>
	<% if @company.errors.any? %>
		<div id="error">
		<h2>
		  <%= pluralize(@company.errors.count, "error") %> Название не сохранено
		</h2>
		<ul>
			<% @company.errors.full_message.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	<p>
	  <%= f.label :title %><br>
	  <%= f.text_field :title %>
	</p>
	<p>
	  <%= f.submit %>
	</p>
<% end %>

app/views/companies/show.html.erb
<p>
  <h2>Company:</h2>
  <%= @company.title %>
</p>

<h2>Vacancies:</h2>
<table>
  <tr>
    <th>Profession</th>
    <th>Country</th>
    <th>City</th>
  </tr>
  <%- @company.jobs.each do |job| %>
    <tr>
    <td><%= job.profession %></td> 
    <td><%= job.country %></td> 
    <td><%= job.city %></td>
    </tr>
   <% end %>
</table>

app/views/home_pages/home.html.erb
<div class="row">
		<section class="col-xs-6">
			<h2>СОИСКАТЕЛЬ</h2>
			<%= link_to "Sign up as a Jobseeker", new_user_registration_path, class: "btn btn-large btn-primary" %>
			<%= link_to 'Sign in', new_user_session_path, class: "btn btn-large btn-primary" %> 
		</section>
		<section class="col-xs-6">
			<h2>РАБОТОДАТЕЬ</h2>
			<%= link_to "Sign up as a Company", '#', class: "btn btn-large btn-primary" %>
		</section>
	</div>
	<section class="container">
		
		<%= link_to "Список компаний с открытыми вакансиями", controller: 'companies' %>

	</section>

app/views/jobs/index.html.erb
<h1>Listing vacancies</h1>
 
<table>
  <tr>
    <th>Profession</th>
    <th>Country</th>
    <th>City</th>
  </tr>
 
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.profession %></td>
      <td><%= job.country %></td>
      <td><%= job.city %></td>
     
    </tr>
  <% end %>

app/views/jobs/new.html.erb
<h1>New Vacancy</h1>
<%= form_for :job, url: company_jobs_path do |f| %>
	
	<p>
	  <%= f.label :profession %><br>
	  <%= f.text_field :profession %>
	</p>

	<p>
	  <%= f.label :country %><br>
	  <%= f.text_field :country %>
	</p>

	<p>
	  <%= f.label :city %><br>
	  <%= f.text_field :city %>
	</p>
	<p>
	  <%= f.submit %>
	</p>

<% end %>

app/views/jobs/show.html.erb
<p>
  <h2>Profession:</h2>
  <%= @job.profession %>
</p>

<p>
	<strong>Country:</strong>
	<%= @job.country %>
</p>

<p>
	<strong>City:</strong>
	<%= @job.city %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vacancy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="hero-unit">
		<h1>VACANCY</h1>
		<p>Добро пожаловать на сайт поиска вакансий</p>
	</header>
	<%= yield %>
</body>
</html>